### ISSUE TITLE
Dont open network interfaces !

### ISSUE THREAD

**Issue by brunopayne** [Jerry1211/PUBG-Radar-master#4]
I compile like the AiYinZiLeGong/PUBG-Radar, but this dont open ! I dont now why :(

**Comment by FrZ-BR** [comment]
@brunopayne

Run in Command Prompt 'java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar < middle_pc_ip > PortFilter < game_pc_ip >

**Comment by brunopayne** [comment]
I have this error when use this command on cmd : C:\Users\EASY\Desktop\PUBG-Radar-master-master (2)\PUBG-Radar-master-master\target>java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.0.1 PortFilter 192.168.0.112
0
Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:47)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:206)
        ... 1 more

C:\Users\EASY\Desktop\PUBG-Radar-master-master (2)\PUBG-Radar-master-master\target>

**Comment by brunopayne** [comment]
now have this on VM : Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\EASY\AppData\Local\Temp\jna-2120706\jna6455770777400933716.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
        at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
        at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
        at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:58)
        at pubg.radar.GameKt.main(Game.kt:47)

C:\Users\EASY\Desktop\PUBG-Radar-master-master (2)\PUBG-Radar-master-master\target>

**Comment by FrZ-BR** [comment]
@brunopayne algo dont forget to add the JAVA_HOME !
