### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by alantody** [Jerry1211/PUBG-Radar-master#8]
Plss help me on this error>>>>>>

Exception in thread "Thread-0" org.pcap4j.core.PcapNativeException: c:\wireshark\test.pcap: No such file or directory
        at org.pcap4j.core.Pcaps.openOffline(Pcaps.java:203)
        at pubg.radar.sniffer.Sniffer$Companion$sniffLocationOffline$1.invoke(Sniffer.kt:156)
        at pubg.radar.sniffer.Sniffer$Companion$sniffLocationOffline$1.invoke(Sniffer.kt:42)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: icons/crate.png
        at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:147)
        at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
        at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
        at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
        at pubg.radar.ui.GLMap.create(GLMap.kt:246)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:364)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
        at pubg.radar.ui.GLMap.show(GLMap.kt:99)
        at pubg.radar.GameKt.main(Game.kt:52)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: icons\crate.png (Internal)
        at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
        at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
        at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:144)
        ... 10 more

**Comment by Marv63** [comment]
Same

**Comment by alantody** [comment]
@Jerry1211 Plss how to setup steb by step?

add me on discord plss help me CodeX#7131

**Comment by Marv63** [comment]
I tryed copying and unaming the box.png into crate.png but it still says, that the icons/crate.png is missing

**Comment by Jerry1211** [comment]
Yeah sorry had it in offline mode, just updated it, let me know if the corpsebox icon works

**Comment by alantody** [comment]
@Jerry1211 Its possible run radar without VM or Middle PC? How?

**Comment by Jerry1211** [comment]
@alantody yes 

> Run in Command Prompt 'java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar <game_pc_ip> PortFilter '

**Comment by alantody** [comment]
@Jerry1211 ok now its works perfectly man nice release

**Comment by alantody** [comment]
@Jerry1211 When I type the command arpspoof <gaming ipv4> in middle pc, my internet pc game close, how to solve this?

**Comment by Jerry1211** [comment]
Dunno, arpsoof causes massive lag i just run the radar on my Game-PC

**Comment by alantody** [comment]
@Jerry1211 Contact me on discord   CodeX#7131   I found one method to run radar in other pc with arpspoof

**Comment by nhkwon** [comment]
@alantody  That is source problem. May be on your source code need to modify. At Game.kt, disabled Sniffer.sniffLocationOffline(), enable Sniffer.sniffLocationOnline(). Or pull the source. Now it is modified.

**Comment by FrZ-BR** [comment]
@alantody lol you "found"... there alot of methods.. but the most used is the VPN with the same IP.... this is not new youg padawan
